# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'oyster' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for oyster
  pod 'tenmax-native-ad-mobile-sdk-ios','~> 1.0.6'

end
